 name: HaxxServer
 version: 1.0.0
 description: This is the main Haxx Backend
 
 author: EssexIO
 
 main: me.EssexIO.Main
 
 commands:
   whitelist:
      description: Whitelist Command
   pl:
      description: List Plugins
   plugins:
      description: List Plugins
   ?:
      description: List Plugins 